# Generated by Django 3.1.5 on 2021-01-31 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('links', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=40)),
                ('transitcarname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category', verbose_name='Category')),
            ],
        ),
    ]
